Repository wp-cli/handbook, pull requests merged in 2024-07, with the labels that each got.

#523 Small typo correction
  how-to-create-custom-plugins.md
Labels: scope:documentation

#525 Fix: Undefined array key warning / Require wp-cli 2.11
  composer.json
Labels: scope:distribution

#524 Add files autoloader for `bin/command.php`
  composer.json
Labels: scope:testing
